from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

TEMPLATES = (
    ROOT
    / "src"
    / "litoral_trace"
    / "templates"
)


def _read(path: str) -> str:
    return (
        TEMPLATES
        / path
    ).read_text(
        encoding="utf-8"
    )


def test_homepage_contains_commercial_polish_sections():
    home = _read(
        "public/home.html"
    )

    for section_id in (
        "platform",
        "eudr",
        "evidence-first",
        "regional-intelligence",
        "security",
        "commercial-cta",
    ):
        assert f'id="{section_id}"' in home


def test_platform_cards_only_target_live_home_sections():
    home = _read(
        "public/home.html"
    )

    allowed_targets = (
        "#eudr",
        "#security",
        "#regional-intelligence",
    )

    for target in allowed_targets:
        assert (
            f'"{target}"'
            in home
        )

    forbidden = (
        'href="/origins"',
        'href="/satellite"',
        'href="/imports"',
        'href="/platform"',
    )

    for target in forbidden:
        assert target not in home


def test_homepage_has_evidence_first_positioning():
    home = _read(
        "public/home.html"
    )

    assert (
        "Built for evidence,"
        in home
    )

    assert (
        "not black-box scoring"
        in home
    )

    assert "Traceable evidence" in home
    assert "Reviewable by design" in home
    assert "Audit-ready structure" in home


def test_homepage_keeps_five_regional_profiles():
    home = _read(
        "public/home.html"
    )

    regions = (
        "Chaco",
        "Corrientes",
        "Misiones",
        "NEA",
        "Argentina",
    )

    for region in regions:
        assert region in home

    # The five cards are generated by one Jinja loop, so the
    # data attribute appears once in source and five times only
    # after template rendering.
    assert (
        'data-regional-profile="{{ region|lower }}"'
        in home
    )

    # Protect the source dataset itself.
    for region in regions:
        assert home.count(
            f'"{region}"'
        ) >= 1


def test_homepage_has_final_commercial_cta():
    home = _read(
        "public/home.html"
    )

    assert (
        "Prepare Argentine origin evidence"
        in home
    )

    assert (
        'href="mailto:comercial@litoraltrace.com"'
        in home
    )

    assert 'href="/login"' in home


def test_login_matches_current_public_brand():
    login = _read(
        "login.html"
    )

    assert (
        '{% extends "public/base_public.html" %}'
        in login
    )

    assert "Corporate workspace" in login
    assert "Sign in to your workspace" in login
    assert "Sign in to workspace" in login

    assert "🪵" not in login
    assert (
        "Exportación Forestal a Europa"
        not in login
    )


def test_login_preserves_security_contract():
    login = _read(
        "login.html"
    )

    assert 'action="/login"' in login
    assert (
        'name="{{ csrf_form_field }}"'
        in login
    )
    assert "{{ csrf_token }}" in login

    assert 'autocomplete="username"' in login
    assert (
        'autocomplete="current-password"'
        in login
    )

    assert 'role="alert"' in login
